### ISSUE TITLE
Make default `deploy_hook_timeout` longer

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-hooks-code#28]
One minute seems quite short considering pagodabox's hook timeout was somewhere around 20 minutes for a while. Maybe 5 mins would be reasonable? (I couldn't find documentation on `deploy_hook_timeout` boxfile setting, so more may be useful)

**Comment by glinton** [comment]
Documentation issue [here](https://github.com/nanobox-io/nanobox-docs/issues/32)

**Comment by notxarb** [comment]
another thing that could be done is alter the error message so it points to the documentation on how to change the hook timeout
