### ISSUE TITLE
some logs aren't getting hooked up to narc

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox-hooks-code#8]
It appears that some logs aren't being shipped to the dashboard. There is some thought that it's just web components. Since webs and workers are configured the same, I can't imagine how this would be true. I'm guessing it's probably something to do with the log_watches.

Here is an app that apparently isn't working:
https://dashboard.bonesalt.com/apps/483c11f0-039b-4aac-9bd1-abad54eb1d7c/logs

**Comment by notxarb** [comment]
That app has no log watches specified.

**Comment by glinton** [comment]
May also be affected by nanopack/narc/issues/1
